trigger: none

pool:
  name: 'DwiPool'
  demands:
    - agent.name -equals dwivm2

parameters:
- name: Environment
  type: string
  default: D
  values:
  - D
  - T
  - O
  - I
  
steps:
  - script: |
      echo "This is the first step"